export enum ModelName {
  ADMIN = 'admins',
  COUNTRY = 'countries',
  CITY = 'cities',
  SETTINGS = 'settings',
  OTP = 'OTP',
  USER = 'users',
  UNIT = 'units',
  UNIT_FAVORITE = 'unit-favorite',
  ORDER = 'orders',
  CONVERSATION = 'conversation',
  CHAT_MESSAGE = 'chat-message',
  STATISTICS = 'statistics',
  NOTIFICATION = 'notifications',
  REFRESH_TOKEN = 'refresh-tokens',
  FORGET_PASSWORD = 'forget-passwords',
  CURRENCY = 'currencies',
  UNIT_TYPE = 'unit-types',
  CONNECTION = 'connections',
  FAVORITE = 'favorites',
  UNIT_RATE = 'unit-rates',
  PUSH_NOTIFICATION = 'push-notifications',
  NOTIFICATION_COUNT = 'notification-counts',
  WALLET = 'wallets',
  WALLET_TRANSACTION = 'wallet-transactions',
  TRANSACTION_CATEGORY = 'transaction-categories',
}
