version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: wallet-mongodb
    command: ['--replSet', 'rs0', '--bind_ip_all']
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGODB_DATABASE=wallet-db
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongosh --quiet) -eq 1
      interval: 10s
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-api
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb:27017/wallet-db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongodb_data:
